name: Swift

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone X']
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild -scheme YotiButtonSDK test -sdk iphonesimulator
    env: 
      destination: ${{ matrix.destination }}
