name: Swift

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 13']
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild -scheme YotiButtonSDK test -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13'
